[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'
remappings = [
'@openzeppelin/=node_modules/@openzeppelin/',
'eth-gas-reporter/=node_modules/eth-gas-reporter/',
'hardhat/=node_modules/hardhat/',
]
gas_reports = ["MultiSigBatRaVot", "BN254", "*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config